typography_spectrum: 0.9530919513199478
color:
  brandStrength: 0.10947711789049208
  lightness: 0.9441640444565564
  saturation: 0.10568022029474378
  rhythmicContrast: 0.4378315096255392
  brandColors:
    - '#5CFF8A'
    - '#45ECFF'
    - '#FFEB00'
    - '#636459'
    - '#CCCECB'
layout_spectrum: 0.331055962247774
name: directly from | rblg
navigation:
  - name: fabric | ch
    url: 'http://www.fabric.ch'
    type: external
  - name: 'fabric | rblg, our survey blog'
    url: 'http://blog.fabric.ch'
    type: external
  - name: 'Selected works, 203 pp, pdf'
    url: 'http://www.fabric.ch/pdf/00_fabric-ch_espaces_moires.pdf'
    type: external
  - name: Follow us on Vimeo
    url: 'https://vimeo.com/fbrcch/videos'
    type: external
title: 'fabric | ch, ongoing works'
